[package]
name = "mnist-nalg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
rand = "0.8.5"
nalgebra = { version = "0.31.0", features = ["rand"] }
